### ISSUE TITLE
Adding metrics for scheduled jobs

### ISSUE THREAD

**Issue by MPV** [leprechaun/gocd-prometheus-exporter#1]
Hi @leprechaun. Awesome initiative! 👍 

What do you think about if we together added support for counting the number of queued jobs in GoCD?

Here's the data source I'm referring to:

>**Get scheduled jobs**
>
>Lists all the current job instances which are scheduled but not yet assigned to any agent.
>
>https://api.gocd.org/current/#get-scheduled-jobs

It seems it's already available in the `Yagocd` API as `Yagocd.jobs.scheduled`. See here:
https://github.com/grundic/yagocd/blob/master/yagocd/resources/job.py#L60-L73

I'm still learning both Python and Prometheus metrics, hence why I decided to start with this discussion before attempting a pull request. Open to hear your thoughts.

**Comment by leprechaun** [comment]
Sweet. That should be pretty easy to tack on.

As I said it's really not quite there yet. I'll put a couple more hours on this and see how it goes.

**Comment by leprechaun** [comment]
Hey, so, here you.

I ended up not using the assigned jobs endpoint, as it returns an XML string, for some reason. However, y looking at what's "building", you can actually see what's queued. The numbers I get should also make a bit more sense.

Here's a dashboard I put together.

![example](https://camo.githubusercontent.com/95290f314b423a1e7f2f267f9eded167bfb97257/68747470733a2f2f692e696d6775722e636f6d2f596d367749726b2e706e67)
