### ISSUE TITLE
error on pipeline operation

### ISSUE THREAD

**Issue by pracplayopen** [leprechaun/gocd-prometheus-exporter#5]
first pipeline operation...

seems it's looking for result of a stage and it's not defined?

w/py2.7 and your code ca81a02
used your pip requirements file to set everything up

unsure of cause but hopefully feedback helps, if you know fix we'd appreciate any help

```
'EasyDict' object has no attribute 'result'


('stage finished', ('PrivateCloud', '179', 'Fetch'))
{'scheduled': True, 'jobs': [{'result': u'Passed', 'state': u'Completed', 'name': u'FetchUpdate', 'scheduled_date': 1530855548456, 'id': 3350}], 'name': u'Fetch', 'can_run': True, 'operate_permission': True, 'approval_type': u'success', 'counter': u'1', 'approved_by': u'changes', 'result': u'Passed', 'rerun_of_counter': None, 'id': 3292}
{'scheduled': False, 'jobs': [], 'name': u'UnitTestBins', 'can_run': True, 'operate_permission': True, 'approval_type': None, 'counter': u'1', 'approved_by': None, 'rerun_of_counter': None, 'id': 0}
Traceback (most recent call last):
  File "gocd_prometheus.py", line 340, in <module>
    stage_finished(i[0], i[3], i[1])
  File "gocd_prometheus.py", line 176, in stage_finished
    is_instance_finished(pipeline_name, pipeline_counter, stage_name)
  File "gocd_prometheus.py", line 161, in is_instance_finished
    stage_results = [s.data.result for s in instance.stages()]
AttributeError: 'EasyDict' object has no attribute 'result'


```

**Comment by pracplayopen** [comment]
seems to still be running ok, just posts errors occasionally like above.

**Comment by leprechaun** [comment]
Fair assumption. Was that the first pipeline run with a new config that *added* a stage? The code, as it is now, doesn't really like it when you go out of it's assumptions (eg, pipeline configs are stable, and you don't cancel jobs)

I'm a little liberal in the handling of exceptions, so, it might not crash, but in doing so, it might be fudging the numbers, which I'm a little more worried about.

I'll be without my GoCD machinery for a few more days while I'm in transit. I'll get on it sooner or later. 

I appreciate those reports, please keep them coming :)

**Comment by pracplayopen** [comment]
no- no config changes.  it occured after the first gocd 'event' (material commit).

have seen the error several times since.  we are getting pipeline metric updates, though frankly i'm not sure how we could compare this to any external reference to determine if it's missing data.

**Comment by pracplayopen** [comment]
very hard to find comparison points as to where these counters relate to anything we know in gocd.

BACKGROUND

We have a large # of pipelines (more than 20),  that said, the gocd pipeline configuration changes quite rarely (perhaps once quarter, if it does it's usually adding a new pipeline not changing existing ones). most of the pipelines are not rebuilt weekly.  only a small subset of pipelines are triggered daily.

QUESTION

These "core" pipelines (iow execute many times a day/week), from gocd console we know how much time these spend in gocd quite well but we don't see anything in either the raw exported stats or the prom queries or graphs that is close.

FOR EXAMPLE

Because we reported errors occuring, we have a script which restarts gocd exporter on a crash, we know running for days but current pid running 1day+:

```
$ ps aux|grep -E "gocd_prometheus|USER"|grep -v grep
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
tc         380  1.8  0.3 270064 27340 ?        Sl   Jul09  27:31 python gocd_prometheus.py
```

from gocd, our "core" pipeline chain takes 10-25+ minutes to execute (depending on how upstream trigger is).  Most of time is from mostly because of testing stages.   pushing several changes we can't find anything close to 10-25min in either raw logs or queries :

```
gocd_job_time_spent_by_state_sum{gocd_url="http://localhost:8153/",job="Run",job_key="pp-XYZ/XYZTest/Run/Run",pipeline="Test",pipeline_group="pp-xyz",stage="Run",stage_key="pp-XYZ/XYZTest/Run",state="Assigned"} 10.0
```

![image](https://user-images.githubusercontent.com/11450154/42495826-d1e70238-83e9-11e8-9ae5-7a2f5b9fbbfc.png)

above graph uses query:

```
sum(gocd_job_time_spent_by_state_sum{state="Assigned",pipeline_group="pp-xyz"})
```

**Comment by pracplayopen** [comment]
the most obvious solution is not to use a framework at all.

gocd lets you export metrics in real time inside of your business process, which is probably the way it should be.

still a useful tool to have summaries generate, but hard to use since no built-in templates.

we open other tickets here, so will close this one.  thx for help
